name: Deploy site

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  DEPLOYING-WEBSITE:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'DEPLOY') || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Deployment Status to In Progress
        run: |
          curl -X PATCH "https://tools-backend.dev.opengig.work/deployment/${{ github.event.repository.name }}" \
            -H "Content-Type: application/json" \
            -d '{"status": "in_progress"}'
      - name: Create or change env file
        run: |
          # Fetch env file from API
          ENV_CONTENT=$(curl -X POST \
            "https://tools-backend.dev.opengig.work/development/${{ github.event.repository.name }}/env" \
            -H "Content-Type: application/json" \
            -d "{\"apiKey\": \"${{ secrets.DEVTOOLS_SECRET }}\"}")
          
          # Write env content directly to file
          echo "$ENV_CONTENT" > .env

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Get Instance Public IP
        id: get_ip
        run: |
          INSTANCE_NAME="${{ github.event.repository.name }}"
          INSTANCE_IP=$(aws lightsail get-instance --instance-name $INSTANCE_NAME --query 'instance.publicIpAddress' --output text)
          echo "INSTANCE_IP=${INSTANCE_IP}" >> $GITHUB_ENV

      - name: SSH into Lightsail Instance and Deploy
        run: |
          # Copy the SSH key
          mkdir -p ~/.ssh
          echo "${{ secrets.DEFAULT_SSH_PRIVATE_KEY }}" > ~/.ssh/github
          chmod 400 ~/.ssh/github

          echo "INSTANCE_IP: $INSTANCE_IP"

          # Deploying Now..!!
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github ubuntu@${{ env.INSTANCE_IP }} 'bash -s' < ./deploy.sh
          curl -X PATCH "https://tools-backend.dev.opengig.work/deployment/${{ github.event.repository.name }}" \
            -H "Content-Type: application/json" \
            -d '{"status": "success"}'
      - name: Set Deployment Status to Failed
        if: failure()
        run: |
          curl -X PATCH "https://tools-backend.dev.opengig.work/deployment/${{ github.event.repository.name }}" \
            -H "Content-Type: application/json" \
            -d '{"status": "failed"}'